apiVersion: v1
kind: Service
metadata:
  name: minecraft-headless
  labels:
    app: minecraft-server
    tier: backend
spec:
  selector:
    app: minecraft-server
    tier: backend
  ports:
    - name: mcserver
      protocol: TCP
      port: 25565
      targetPort: 25565
  type: NodePort