apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-server
spec:
  serviceName: minecraft-headless
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: minecraft-server
        tier: backend
        track: stable
    spec:
      restartPolicy: Always
      containers:
        - name: minecraft-server
          image:  balmiusf/mcserver:latest
          command: 
            - java
            - -jar
            - /minecraft/server.jar
          env:
            - name: JAVA_MEM_SIZE
              value: "1g"
          ports:
            - name: mcserver
              containerPort: 25565 
#          resources:
#            requests:
#             memory: 1Gi  
#              cpu: "1"
          volumeMounts:
            - name: world-data
              mountPath: minecraft/world/
            - name: minecraft-config
              mountPath: minecraft/server.properties
              subPath: server.properties    
            - name: minecraft-config
              mountPath: minecraft/eula.txt
              subPath: eula.txt      
      volumes:
        - name: minecraft-config
          configMap:
            name: minecraft-configuration
  volumeClaimTemplates:
  - metadata:
      name: world-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi