apiVersion: v1
kind: Service
metadata:
  name: minecraft-ftb-headless
  labels:
    app: minecraft-ftb-server
    tier: backend
spec:
  selector:
    app: minecraft-ftb-server
    tier: backend
  ports:
    - name: mc-ftb-server
      protocol: TCP
      port: 25565
      targetPort: 25565
  type: NodePort